# Copyright (c) 2026, Omnexa and contributors
# License: MIT

"""DocType definitions for enterprise gap closure wave 2."""

from __future__ import annotations

GAP_CLOSURE_WAVE2_DOCTYPES: list[dict] = [
	{
		"name": "Healthcare Appointment Waitlist",
		"autoname": "naming_series:",
		"naming_series": "AWL-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "AWL-.#####", "reqd": 1, "default": "AWL-.#####"}),
			("patient", "Link", "Patient", {"options": "Healthcare Patient", "reqd": 1, "in_list_view": 1}),
			("practitioner", "Link", "Practitioner", {"options": "Healthcare Practitioner", "in_list_view": 1}),
			("specialty", "Link", "Specialty", {"options": "Healthcare Specialty"}),
			("preferred_date", "Date", "Preferred date", {"in_list_view": 1}),
			("priority", "Select", "Priority", {"options": "Normal\nHigh\nUrgent", "default": "Normal"}),
			("status", "Select", "Status", {"options": "Waiting\nNotified\nBooked\nCancelled", "default": "Waiting", "in_list_view": 1}),
			("appointment", "Link", "Booked appointment", {"options": "Healthcare Appointment"}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
			("notes", "Small Text", "Notes"),
		],
	},
	{
		"name": "Healthcare Telehealth Session",
		"autoname": "naming_series:",
		"naming_series": "THS-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "THS-.#####", "reqd": 1, "default": "THS-.#####"}),
			("appointment", "Link", "Appointment", {"options": "Healthcare Appointment", "reqd": 1, "in_list_view": 1}),
			("patient", "Link", "Patient", {"options": "Healthcare Patient", "reqd": 1, "in_list_view": 1}),
			("practitioner", "Link", "Practitioner", {"options": "Healthcare Practitioner", "reqd": 1}),
			("room_id", "Data", "Room ID", {"in_list_view": 1}),
			("join_url", "Data", "Join URL"),
			("waiting_room_status", "Select", "Waiting room", {"options": "Not Joined\nPatient Waiting\nProvider Joined\nIn Session", "default": "Not Joined"}),
			("status", "Select", "Status", {"options": "Scheduled\nWaiting\nIn Progress\nCompleted\nCancelled", "default": "Scheduled", "in_list_view": 1}),
			("started_at", "Datetime", "Started at"),
			("ended_at", "Datetime", "Ended at"),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Home Visit Request",
		"autoname": "naming_series:",
		"naming_series": "HVR-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "HVR-.#####", "reqd": 1, "default": "HVR-.#####"}),
			("patient", "Link", "Patient", {"options": "Healthcare Patient", "reqd": 1, "in_list_view": 1}),
			("visit_type", "Select", "Visit type", {"options": "Doctor\nNursing\nPhysiotherapy\nLab Collection", "reqd": 1, "in_list_view": 1}),
			("scheduled_datetime", "Datetime", "Scheduled", {"in_list_view": 1}),
			("address", "Small Text", "Address", {"reqd": 1}),
			("practitioner", "Link", "Assigned practitioner", {"options": "Healthcare Practitioner"}),
			("status", "Select", "Status", {"options": "Requested\nScheduled\nIn Transit\nCompleted\nCancelled", "default": "Requested", "in_list_view": 1}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
			("notes", "Small Text", "Notes"),
		],
	},
	{
		"name": "Healthcare Remote Monitoring Reading",
		"autoname": "naming_series:",
		"naming_series": "RPM-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "RPM-.#####", "reqd": 1, "default": "RPM-.#####"}),
			("patient", "Link", "Patient", {"options": "Healthcare Patient", "reqd": 1, "in_list_view": 1}),
			("device_id", "Data", "Device ID"),
			("metric_type", "Select", "Metric", {"options": "Blood Pressure\nHeart Rate\nSpO2\nGlucose\nWeight\nTemperature", "reqd": 1, "in_list_view": 1}),
			("value", "Float", "Value", {"reqd": 1, "in_list_view": 1}),
			("unit", "Data", "Unit"),
			("reading_datetime", "Datetime", "Reading time", {"reqd": 1, "in_list_view": 1}),
			("alert_level", "Select", "Alert", {"options": "Normal\nWarning\nCritical", "default": "Normal"}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Patient Dependent",
		"autoname": "naming_series:",
		"naming_series": "DEP-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "DEP-.#####", "reqd": 1, "default": "DEP-.#####"}),
			("guardian_patient", "Link", "Guardian patient", {"options": "Healthcare Patient", "reqd": 1, "in_list_view": 1}),
			("dependent_patient", "Link", "Dependent patient", {"options": "Healthcare Patient", "reqd": 1, "in_list_view": 1}),
			("relationship", "Select", "Relationship", {"options": "Child\nSpouse\nParent\nSibling\nOther", "reqd": 1}),
			("is_active", "Check", "Active", {"default": "1", "in_list_view": 1}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Nursing Incident Report",
		"autoname": "naming_series:",
		"naming_series": "NIR-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "NIR-.#####", "reqd": 1, "default": "NIR-.#####"}),
			("patient", "Link", "Patient", {"options": "Healthcare Patient", "reqd": 1, "in_list_view": 1}),
			("admission", "Link", "Admission", {"options": "Healthcare Admission"}),
			("incident_type", "Select", "Type", {"options": "Fall\nMedication Error\nPressure Injury\nEquipment\nOther", "reqd": 1, "in_list_view": 1}),
			("severity", "Select", "Severity", {"options": "Low\nMedium\nHigh\nSentinel", "default": "Low", "in_list_view": 1}),
			("reported_by", "Link", "Reported by", {"options": "User", "reqd": 1}),
			("incident_datetime", "Datetime", "Incident time", {"reqd": 1}),
			("description", "Text", "Description", {"reqd": 1}),
			("status", "Select", "Status", {"options": "Open\nUnder Review\nClosed", "default": "Open", "in_list_view": 1}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Nursing Shift Handover",
		"autoname": "naming_series:",
		"naming_series": "NSH-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "NSH-.#####", "reqd": 1, "default": "NSH-.#####"}),
			("from_nurse", "Link", "From nurse", {"options": "User", "reqd": 1, "in_list_view": 1}),
			("to_nurse", "Link", "To nurse", {"options": "User", "reqd": 1, "in_list_view": 1}),
			("shift_date", "Date", "Shift date", {"reqd": 1, "in_list_view": 1}),
			("ward", "Link", "Ward", {"options": "Healthcare Service Unit"}),
			("summary", "Text", "Handover summary", {"reqd": 1}),
			("pending_tasks", "Text", "Pending tasks"),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Medical Tourism Case",
		"autoname": "naming_series:",
		"naming_series": "MTC-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "MTC-.#####", "reqd": 1, "default": "MTC-.#####"}),
			("patient", "Link", "Patient", {"options": "Healthcare Patient", "reqd": 1, "in_list_view": 1}),
			("country_of_origin", "Data", "Country of origin", {"in_list_view": 1}),
			("treatment_package", "Link", "Treatment package", {"options": "Healthcare Treatment Package"}),
			("coordinator", "Link", "Coordinator", {"options": "User"}),
			("visa_status", "Select", "Visa status", {"options": "Not Required\nPending\nApproved\nOn Hold"}),
			("arrival_date", "Date", "Arrival date"),
			("status", "Select", "Status", {"options": "Inquiry\nPlanning\nIn Treatment\nDischarged\nCancelled", "default": "Inquiry", "in_list_view": 1}),
			("concierge_notes", "Text", "Concierge notes"),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Cpt Code",
		"autoname": "field:cpt_code",
		"fields": [
			("cpt_code", "Data", "CPT code", {"reqd": 1, "unique": 1, "in_list_view": 1}),
			("description", "Data", "Description", {"reqd": 1, "in_list_view": 1}),
			("category", "Select", "Category", {"options": "Evaluation\nProcedure\nSurgery\nRadiology\nLab\nAnesthesia\nOther"}),
			("default_rate", "Currency", "Default rate"),
			("is_active", "Check", "Active", {"default": "1", "in_list_view": 1}),
		],
	},
	{
		"name": "Healthcare Penetration Test Report",
		"autoname": "naming_series:",
		"naming_series": "PTR-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "PTR-.#####", "reqd": 1, "default": "PTR-.#####"}),
			("test_date", "Date", "Test date", {"reqd": 1, "in_list_view": 1}),
			("vendor", "Data", "Vendor", {"in_list_view": 1}),
			("scope", "Small Text", "Scope", {"reqd": 1}),
			("findings_count", "Int", "Findings", {"default": "0"}),
			("critical_count", "Int", "Critical findings", {"default": "0"}),
			("status", "Select", "Status", {"options": "Planned\nIn Progress\nCompleted", "default": "Completed", "in_list_view": 1}),
			("report_url", "Data", "Report URL"),
			("next_test_date", "Date", "Next test date"),
		],
	},
	{
		"name": "Healthcare Disaster Recovery Plan",
		"autoname": "field:plan_name",
		"fields": [
			("plan_name", "Data", "Plan name", {"reqd": 1, "unique": 1, "in_list_view": 1}),
			("last_test_date", "Date", "Last DR test", {"in_list_view": 1}),
			("rto_hours", "Int", "RTO (hours)", {"default": "4"}),
			("rpo_hours", "Int", "RPO (hours)", {"default": "1"}),
			("test_result", "Select", "Last test result", {"options": "Pass\nPass with notes\nFail", "in_list_view": 1}),
			("runbook_content", "Text", "Runbook"),
			("is_active", "Check", "Active", {"default": "1"}),
		],
	},
	{
		"name": "Healthcare Pacs Endpoint",
		"autoname": "field:endpoint_name",
		"fields": [
			("endpoint_name", "Data", "Endpoint name", {"reqd": 1, "unique": 1, "in_list_view": 1}),
			("base_url", "Data", "Base URL", {"reqd": 1, "in_list_view": 1}),
			("role", "Select", "Role", {"options": "Primary\nSecondary\nArchive", "default": "Primary", "in_list_view": 1}),
			("priority", "Int", "Priority", {"default": "1"}),
			("is_active", "Check", "Active", {"default": "1"}),
			("health_status", "Select", "Health", {"options": "Healthy\nDegraded\nDown", "default": "Healthy"}),
		],
	},
	{
		"name": "Healthcare Home Lab Collection Request",
		"autoname": "naming_series:",
		"naming_series": "HLCR-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "HLCR-.#####", "reqd": 1, "default": "HLCR-.#####"}),
			("patient", "Link", "Patient", {"options": "Healthcare Patient", "reqd": 1, "in_list_view": 1}),
			("service_request", "Link", "Lab order", {"options": "Healthcare Service Request"}),
			("scheduled_datetime", "Datetime", "Scheduled", {"in_list_view": 1}),
			("address", "Small Text", "Address", {"reqd": 1}),
			("phlebotomist", "Link", "Phlebotomist", {"options": "Healthcare Practitioner"}),
			("status", "Select", "Status", {"options": "Requested\nScheduled\nCollected\nCancelled", "default": "Requested", "in_list_view": 1}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Patient Payment Checkout",
		"autoname": "naming_series:",
		"naming_series": "PAY-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "PAY-.#####", "reqd": 1, "default": "PAY-.#####"}),
			("patient", "Link", "Patient", {"options": "Healthcare Patient", "reqd": 1, "in_list_view": 1}),
			("amount", "Currency", "Amount", {"reqd": 1, "in_list_view": 1}),
			("service_charge", "Link", "Service charge", {"options": "Healthcare Service Charge"}),
			("payment_reference", "Data", "Payment reference"),
			("checkout_url", "Data", "Checkout URL"),
			("status", "Select", "Status", {"options": "Pending\nPaid\nFailed\nCancelled", "default": "Pending", "in_list_view": 1}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch"}),
		],
	},
]

DEFAULT_CPT_CODES = [
	("99213", "Office visit — established patient, level 3", "Evaluation", 150),
	("99214", "Office visit — established patient, level 4", "Evaluation", 220),
	("99203", "Office visit — new patient, level 3", "Evaluation", 200),
	("93000", "Electrocardiogram, complete", "Procedure", 80),
	("71046", "Chest X-ray, 2 views", "Radiology", 120),
	("80053", "Comprehensive metabolic panel", "Lab", 65),
	("85025", "Complete blood count (CBC)", "Lab", 45),
	("27447", "Total knee arthroplasty", "Surgery", 15000),
	("45378", "Colonoscopy, diagnostic", "Procedure", 900),
	("96372", "Therapeutic injection, subcutaneous/intramuscular", "Procedure", 35),
]
