# Copyright (c) 2026, Omnexa and contributors
# License: MIT

"""DocType definitions for world-class gap closure wave 4 (Blood Bank, CSSD, Compensation, QMS)."""

from __future__ import annotations

GAP_CLOSURE_WAVE4_DOCTYPES: list[dict] = [
	{
		"name": "Healthcare Blood Donor",
		"autoname": "naming_series:",
		"naming_series": "BDN-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "BDN-.#####", "reqd": 1, "default": "BDN-.#####"}),
			("donor_name", "Data", "Donor name", {"reqd": 1, "in_list_view": 1}),
			("blood_group", "Select", "Blood group", {"options": "A+\nA-\nB+\nB-\nAB+\nAB-\nO+\nO-", "reqd": 1, "in_list_view": 1}),
			("phone", "Data", "Phone"),
			("last_donation_date", "Date", "Last donation", {"in_list_view": 1}),
			("status", "Select", "Status", {"options": "Active\nDeferred\nInactive", "default": "Active", "in_list_view": 1}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Blood Unit",
		"autoname": "naming_series:",
		"naming_series": "BUN-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "BUN-.#####", "reqd": 1, "default": "BUN-.#####"}),
			("unit_number", "Data", "Unit number", {"reqd": 1, "unique": 1, "in_list_view": 1}),
			("blood_group", "Select", "Blood group", {"options": "A+\nA-\nB+\nB-\nAB+\nAB-\nO+\nO-", "reqd": 1, "in_list_view": 1}),
			("component", "Select", "Component", {"options": "Whole Blood\nPacked RBC\nPlatelets\nFFP\nCryoprecipitate", "default": "Packed RBC", "in_list_view": 1}),
			("donor", "Link", "Donor", {"options": "Healthcare Blood Donor"}),
			("collection_date", "Date", "Collection date", {"reqd": 1}),
			("expiry_date", "Date", "Expiry date", {"reqd": 1, "in_list_view": 1}),
			("status", "Select", "Status", {"options": "Quarantine\nAvailable\nReserved\nIssued\nDiscarded", "default": "Available", "in_list_view": 1}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Transfusion Order",
		"autoname": "naming_series:",
		"naming_series": "TRF-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "TRF-.#####", "reqd": 1, "default": "TRF-.#####"}),
			("patient", "Link", "Patient", {"options": "Healthcare Patient", "reqd": 1, "in_list_view": 1}),
			("admission", "Link", "Admission", {"options": "Healthcare Admission"}),
			("blood_unit", "Link", "Blood unit", {"options": "Healthcare Blood Unit", "in_list_view": 1}),
			("cross_match_result", "Select", "Cross match", {"options": "Pending\nCompatible\nIncompatible", "default": "Pending", "in_list_view": 1}),
			("ordered_by", "Link", "Ordered by", {"options": "Healthcare Practitioner"}),
			("status", "Select", "Status", {"options": "Draft\nCross Match\nApproved\nTransfused\nCancelled", "default": "Draft", "in_list_view": 1}),
			("transfusion_datetime", "Datetime", "Transfusion time"),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Cssd Instrument",
		"autoname": "field:instrument_code",
		"fields": [
			("instrument_code", "Data", "Instrument code", {"reqd": 1, "unique": 1, "in_list_view": 1}),
			("instrument_name", "Data", "Instrument name", {"reqd": 1, "in_list_view": 1}),
			("instrument_type", "Select", "Type", {"options": "Forceps\nScissors\nRetractor\nTray\nSet\nOther", "default": "Set"}),
			("status", "Select", "Status", {"options": "In Use\nIn CSSD\nSterile\nExpired", "default": "Sterile", "in_list_view": 1}),
			("last_sterilization_date", "Date", "Last sterilization"),
			("sterility_expiry_date", "Date", "Sterility expiry", {"in_list_view": 1}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Sterilization Cycle",
		"autoname": "naming_series:",
		"naming_series": "CSS-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "CSS-.#####", "reqd": 1, "default": "CSS-.#####"}),
			("instrument", "Link", "Instrument", {"options": "Healthcare Cssd Instrument", "reqd": 1, "in_list_view": 1}),
			("cycle_type", "Select", "Cycle type", {"options": "Wash\nPack\nAutoclave\nStorage\nIssue", "reqd": 1, "in_list_view": 1}),
			("cycle_datetime", "Datetime", "Cycle time", {"reqd": 1, "in_list_view": 1}),
			("operator", "Link", "Operator", {"options": "User"}),
			("result", "Select", "Result", {"options": "Pass\nFail\nPending", "default": "Pass", "in_list_view": 1}),
			("notes", "Small Text", "Notes"),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Physician Compensation Rule",
		"autoname": "field:rule_code",
		"fields": [
			("rule_code", "Data", "Rule code", {"reqd": 1, "unique": 1, "in_list_view": 1}),
			("practitioner", "Link", "Practitioner", {"options": "Healthcare Practitioner", "reqd": 1, "in_list_view": 1}),
			("compensation_model", "Select", "Model", {"options": "Fixed Salary\nRevenue Share\nPer Visit\nPer Procedure\nPer Surgery\nHourly\nTiered Commission", "reqd": 1, "in_list_view": 1}),
			("share_percent", "Percent", "Share %"),
			("fixed_amount", "Currency", "Fixed amount"),
			("effective_from", "Date", "Effective from", {"reqd": 1}),
			("effective_to", "Date", "Effective to"),
			("is_active", "Check", "Active", {"default": "1", "in_list_view": 1}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Physician Settlement",
		"autoname": "naming_series:",
		"naming_series": "PST-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "PST-.#####", "reqd": 1, "default": "PST-.#####"}),
			("practitioner", "Link", "Practitioner", {"options": "Healthcare Practitioner", "reqd": 1, "in_list_view": 1}),
			("period_start", "Date", "Period start", {"reqd": 1, "in_list_view": 1}),
			("period_end", "Date", "Period end", {"reqd": 1, "in_list_view": 1}),
			("gross_revenue", "Currency", "Gross revenue", {"in_list_view": 1}),
			("physician_share", "Currency", "Physician share", {"in_list_view": 1}),
			("status", "Select", "Status", {"options": "Draft\nApproved\nPaid", "default": "Draft", "in_list_view": 1}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Quality Corrective Action",
		"autoname": "naming_series:",
		"naming_series": "CAPA-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "CAPA-.#####", "reqd": 1, "default": "CAPA-.#####"}),
			("title", "Data", "Title", {"reqd": 1, "in_list_view": 1}),
			("source", "Select", "Source", {"options": "Incident\nAudit\nPatient Complaint\nNear Miss", "reqd": 1}),
			("severity", "Select", "Severity", {"options": "Low\nMedium\nHigh\nCritical", "default": "Medium", "in_list_view": 1}),
			("root_cause", "Text", "Root cause analysis"),
			("corrective_action", "Text", "Corrective action"),
			("status", "Select", "Status", {"options": "Open\nIn Progress\nVerified\nClosed", "default": "Open", "in_list_view": 1}),
			("due_date", "Date", "Due date"),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Infection Surveillance Case",
		"autoname": "naming_series:",
		"naming_series": "INF-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "INF-.#####", "reqd": 1, "default": "INF-.#####"}),
			("patient", "Link", "Patient", {"options": "Healthcare Patient", "reqd": 1, "in_list_view": 1}),
			("admission", "Link", "Admission", {"options": "Healthcare Admission"}),
			("infection_type", "Select", "Infection type", {"options": "HAI\nSSI\nCAUTI\nCLABSI\nVAP\nOther", "reqd": 1, "in_list_view": 1}),
			("onset_date", "Date", "Onset date", {"reqd": 1, "in_list_view": 1}),
			("isolation_required", "Check", "Isolation required"),
			("status", "Select", "Status", {"options": "Active\nResolved\nUnder Surveillance", "default": "Active", "in_list_view": 1}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
]
