# Copyright (c) 2026, Omnexa and contributors
# License: MIT

"""DocType definitions for Wave 7 — Global ePrescription."""

from __future__ import annotations

GAP_CLOSURE_WAVE7_DOCTYPES: list[dict] = [
	{
		"name": "Healthcare Medication Request Item",
		"istable": True,
		"autoname": "hash",
		"fields": [
			("drug_name", "Data", "Drug name", {"reqd": 1, "in_list_view": 1}),
			("rxnorm_code", "Link", "RxNorm", {"options": "Healthcare Rxnorm Code", "in_list_view": 1}),
			("formulary_item", "Link", "Formulary", {"options": "Healthcare Drug Formulary"}),
			("dose", "Data", "Dose", {"in_list_view": 1}),
			("route", "Select", "Route", {"options": "Oral\nIV\nIM\nSC\nTopical\nInhalation\nOther", "default": "Oral"}),
			("frequency", "Data", "Frequency", {"in_list_view": 1}),
			("duration_days", "Int", "Duration (days)"),
			("quantity", "Float", "Quantity", {"default": "1"}),
			("instructions", "Small Text", "Instructions"),
			("is_controlled_substance", "Check", "Controlled substance", {"default": "0"}),
		],
	},
	{
		"name": "Healthcare Medication Request",
		"is_submittable": True,
		"autoname": "naming_series:",
		"naming_series": "HMR-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "HMR-.#####", "reqd": 1, "default": "HMR-.#####"}),
			("patient", "Link", "Patient", {"options": "Healthcare Patient", "reqd": 1, "in_list_view": 1}),
			("practitioner", "Link", "Prescriber", {"options": "Healthcare Practitioner", "reqd": 1, "in_list_view": 1}),
			("encounter", "Link", "Encounter", {"options": "Healthcare Encounter"}),
			("status", "Select", "Status", {"options": "Draft\nSigned\nDispensed\nCancelled", "default": "Draft", "in_list_view": 1, "read_only": 1}),
			("diagnosis", "Small Text", "Diagnosis / indication", {"reqd": 1}),
			("icd10_code", "Data", "ICD-10"),
			("icd11_code", "Data", "ICD-11"),
			("items", "Table", "Medications", {"options": "Healthcare Medication Request Item", "reqd": 1}),
			("signed_on", "Datetime", "Signed on", {"read_only": 1}),
			("signed_by", "Link", "Signed by", {"options": "User", "read_only": 1}),
			("signature_hash", "Data", "Signature hash", {"read_only": 1}),
			("qr_token", "Data", "QR token", {"read_only": 1}),
			("verified_by_pharmacist", "Link", "Verified by", {"options": "User", "read_only": 1}),
			("verified_on", "Datetime", "Verified on", {"read_only": 1}),
			("dispense_reference", "Link", "Dispense", {"options": "Healthcare Medication Dispense", "read_only": 1}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Prescription Signature",
		"autoname": "hash",
		"fields": [
			("medication_request", "Link", "Medication Request", {"options": "Healthcare Medication Request", "reqd": 1, "in_list_view": 1}),
			("signed_by", "Link", "Signed by", {"options": "User", "reqd": 1, "in_list_view": 1}),
			("signed_on", "Datetime", "Signed on", {"reqd": 1, "default": "Now"}),
			("signature_hash", "Data", "Signature hash", {"reqd": 1, "in_list_view": 1}),
			("algorithm", "Data", "Algorithm", {"default": "SHA256"}),
			("payload_json", "Long Text", "Signed payload (JSON)"),
		],
	},
	{
		"name": "Healthcare Cds Alert Log",
		"autoname": "naming_series:",
		"naming_series": "CAL-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "CAL-.#####", "reqd": 1, "default": "CAL-.#####"}),
			("medication_request", "Link", "Medication Request", {"options": "Healthcare Medication Request", "in_list_view": 1}),
			("patient", "Link", "Patient", {"options": "Healthcare Patient", "reqd": 1, "in_list_view": 1}),
			("check_type", "Select", "Check type", {"options": "Drug-Drug\nDrug-Allergy\nDrug-Disease\nPregnancy\nLactation\nPediatric\nGeriatric\nRenal\nHepatic\nDuplicate\nMax Dose\nOther", "reqd": 1, "in_list_view": 1}),
			("severity", "Select", "Severity", {"options": "Info\nWarning\nCritical\nContraindicated", "default": "Warning", "in_list_view": 1}),
			("message", "Text", "Message", {"reqd": 1}),
			("overridden", "Check", "Overridden", {"default": "0", "in_list_view": 1}),
			("override_reason", "Small Text", "Override reason"),
			("overridden_by", "Link", "Overridden by", {"options": "User"}),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
	{
		"name": "Healthcare Drug Formulary",
		"autoname": "field:formulary_code",
		"fields": [
			("formulary_code", "Data", "Formulary code", {"reqd": 1, "unique": 1, "in_list_view": 1}),
			("drug_name", "Data", "Drug name", {"reqd": 1, "in_list_view": 1}),
			("rxnorm_code", "Link", "RxNorm", {"options": "Healthcare Rxnorm Code", "in_list_view": 1}),
			("generic_name", "Data", "Generic name", {"in_list_view": 1}),
			("strength", "Data", "Strength"),
			("dosage_form", "Data", "Dosage form"),
			("is_controlled", "Check", "Controlled substance", {"default": "0", "in_list_view": 1}),
			("schedule_class", "Select", "Schedule", {"options": "\nII\nIII\nIV\nV"}),
			("is_active", "Check", "Active", {"default": "1", "in_list_view": 1}),
			("max_daily_dose", "Float", "Max daily dose"),
			("pregnancy_category", "Select", "Pregnancy category", {"options": "\nA\nB\nC\nD\nX"}),
			("renal_adjustment_notes", "Small Text", "Renal adjustment"),
			("hepatic_adjustment_notes", "Small Text", "Hepatic adjustment"),
			("company", "Link", "Company", {"options": "Company"}),
		],
	},
	{
		"name": "Healthcare Rxnorm Code",
		"autoname": "field:rxnorm_cui",
		"fields": [
			("rxnorm_cui", "Data", "RxNorm CUI", {"reqd": 1, "unique": 1, "in_list_view": 1}),
			("drug_name", "Data", "Drug name", {"reqd": 1, "in_list_view": 1}),
			("generic_name", "Data", "Generic name", {"in_list_view": 1}),
			("strength", "Data", "Strength"),
			("dosage_form", "Data", "Dosage form"),
			("is_active", "Check", "Active", {"default": "1", "in_list_view": 1}),
		],
	},
	{
		"name": "Healthcare Pharmacy Substitution Log",
		"autoname": "naming_series:",
		"naming_series": "PSL-.#####",
		"fields": [
			("naming_series", "Select", "Series", {"options": "PSL-.#####", "reqd": 1, "default": "PSL-.#####"}),
			("medication_request", "Link", "Medication Request", {"options": "Healthcare Medication Request", "reqd": 1, "in_list_view": 1}),
			("original_drug", "Data", "Original drug", {"reqd": 1, "in_list_view": 1}),
			("substituted_drug", "Data", "Substituted drug", {"reqd": 1, "in_list_view": 1}),
			("reason", "Select", "Reason", {"options": "Generic\nStock unavailable\nFormulary\nPatient request\nOther", "reqd": 1}),
			("pharmacist", "Link", "Pharmacist", {"options": "User", "reqd": 1}),
			("notes", "Small Text", "Notes"),
			("company", "Link", "Company", {"options": "Company", "reqd": 1}),
			("branch", "Link", "Branch", {"options": "Branch", "reqd": 1}),
		],
	},
]

# Core RxNorm seed — patch expands strengths/forms to 1000+
RXNORM_BASE_DRUGS: list[tuple[str, str, str]] = [
	("161", "Acetaminophen", "Acetaminophen"),
	("197361", "Amlodipine", "Amlodipine"),
	("197380", "Atenolol", "Atenolol"),
	("197381", "Atorvastatin", "Atorvastatin"),
	("197392", "Azithromycin", "Azithromycin"),
	("197454", "Ciprofloxacin", "Ciprofloxacin"),
	("197511", "Doxycycline", "Doxycycline"),
	("197541", "Enalapril", "Enalapril"),
	("197591", "Furosemide", "Furosemide"),
	("197604", "Gabapentin", "Gabapentin"),
	("197625", "Hydrochlorothiazide", "Hydrochlorothiazide"),
	("197636", "Ibuprofen", "Ibuprofen"),
	("197690", "Lisinopril", "Lisinopril"),
	("197696", "Losartan", "Losartan"),
	("197737", "Metformin", "Metformin"),
	("197747", "Metoprolol", "Metoprolol"),
	("197806", "Omeprazole", "Omeprazole"),
	("197884", "Prednisone", "Prednisone"),
	("197903", "Ranitidine", "Ranitidine"),
	("198014", "Simvastatin", "Simvastatin"),
	("198211", "Warfarin", "Warfarin"),
	("198440", "Amoxicillin", "Amoxicillin"),
	("199362", "Insulin Glargine", "Insulin glargine"),
	("200033", "Clopidogrel", "Clopidogrel"),
	("200345", "Levothyroxine", "Levothyroxine"),
	("200809", "Salbutamol", "Albuterol"),
	("201267", "Pantoprazole", "Pantoprazole"),
	("203214", "Rosuvastatin", "Rosuvastatin"),
	("204442", "Tamsulosin", "Tamsulosin"),
	("205322", "Sertraline", "Sertraline"),
	("20610", "Morphine", "Morphine"),
	("206833", "Tramadol", "Tramadol"),
	("207106", "Celecoxib", "Celecoxib"),
	("208161", "Montelukast", "Montelukast"),
	("209387", "Escitalopram", "Escitalopram"),
	("2101", "Codeine", "Codeine"),
	("2116", "Carbamazepine", "Carbamazepine"),
	("214582", "Empagliflozin", "Empagliflozin"),
	("2160", "Cephalexin", "Cephalexin"),
	("2180", "Cefuroxime", "Cefuroxime"),
	("2194", "Ceftriaxone", "Ceftriaxone"),
	("221147", "Dapagliflozin", "Dapagliflozin"),
	("224905", "Apixaban", "Apixaban"),
	("226716", "Rivaroxaban", "Rivaroxaban"),
	("227518", "Empagliflozin/Metformin", "Empagliflozin / Metformin"),
	("233698", "Sitagliptin", "Sitagliptin"),
	("235473", "Linagliptin", "Linagliptin"),
	("236374", "Semaglutide", "Semaglutide"),
	("239081", "Dulaglutide", "Dulaglutide"),
	("2418", "Chlorpheniramine", "Chlorpheniramine"),
	("243670", "Ticagrelor", "Ticagrelor"),
	("245314", "Sacubitril/Valsartan", "Sacubitril / Valsartan"),
]

RXNORM_STRENGTHS = ["5 mg", "10 mg", "20 mg", "25 mg", "50 mg", "100 mg", "250 mg", "500 mg", "850 mg", "1000 mg"]
RXNORM_FORMS = ["Tablet", "Capsule", "Solution", "Suspension", "Injection", "Cream", "Inhaler"]
