# Copyright (c) 2026, Omnexa and contributors
# License: MIT

"""World-class hospital demo catalog — all specialties, clinics, practitioners, patients."""

from __future__ import annotations

# (code, label, unit_type)
DEPARTMENTS: list[tuple[str, str, str]] = [
	("FM", "Family Medicine", "Clinic"),
	("OPD", "General Outpatient", "Clinic"),
	("CARD", "Cardiology", "Clinic"),
	("NEU", "Neurology", "Clinic"),
	("PED", "Pediatrics", "Clinic"),
	("NEO", "Neonatology", "Clinic"),
	("OBG", "Obstetrics & Gynecology", "Clinic"),
	("IVF", "Fertility & IVF", "Clinic"),
	("ORT", "Orthopedics", "Clinic"),
	("SUR", "General Surgery", "Service Unit"),
	("DER", "Dermatology", "Clinic"),
	("OPH", "Ophthalmology", "Clinic"),
	("ENT", "ENT", "Clinic"),
	("DEN", "Dental Center", "Clinic"),
	("URO", "Urology", "Clinic"),
	("ONC", "Oncology", "Clinic"),
	("PSY", "Psychiatry", "Clinic"),
	("END", "Endocrinology", "Clinic"),
	("GAS", "Gastroenterology", "Clinic"),
	("PUL", "Pulmonology", "Clinic"),
	("NEP", "Nephrology", "Clinic"),
	("RHE", "Rheumatology", "Clinic"),
	("INF", "Infectious Diseases", "Clinic"),
	("PTH", "Physiotherapy", "Clinic"),
	("SLP", "Speech Therapy", "Clinic"),
	("OCC", "Occupational Therapy", "Clinic"),
	("DIA", "Dialysis Center", "Service Unit"),
	("RAD", "Radiology", "Service Unit"),
	("LAB", "Laboratory", "Service Unit"),
	("PHM", "Pharmacy", "Pharmacy"),
	("ER", "Emergency", "Emergency"),
	("IPD", "Inpatient Ward", "Ward"),
	("ICU", "Intensive Care Unit", "ICU"),
	("NICU", "Neonatal ICU", "NICU"),
	("CMP", "Companion Lodging", "Companion Ward"),
	("OT", "Operating Theatre", "Service Unit"),
	("BBK", "Blood Bank", "Service Unit"),
	("CSS", "Central Sterile Supply", "Service Unit"),
	("BME", "Biomedical Engineering", "Service Unit"),
]

# (practitioner_key, display_name, specialty_label, dept_code)
PRACTITIONERS: list[tuple[str, str, str, str]] = [
	("FM", "Dr. Nadia Farouk", "General Medicine", "FM"),
	("GEN", "Dr. Sami Rashad", "General Medicine", "OPD"),
	("CAR", "Dr. Omar Khalil", "Cardiology", "CARD"),
	("NEU", "Dr. Rania Saleh", "Neurology", "NEU"),
	("PED", "Dr. Sara Mahmoud", "Pediatrics", "PED"),
	("NEO", "Dr. Lina Hafez", "Pediatrics", "NEO"),
	("OBG", "Dr. Hala Refaat", "Gynecology", "OBG"),
	("IVF", "Dr. Mona Zaki", "Gynecology", "IVF"),
	("ORT", "Dr. Hisham Nabil", "Orthopedics", "ORT"),
	("SUR", "Dr. Adel Mansour", "Surgery", "SUR"),
	("DER", "Dr. Laila Samir", "Dermatology", "DER"),
	("OPH", "Dr. Youssef Anwar", "Ophthalmology", "OPH"),
	("ENT", "Dr. Karim Nasr", "ENT", "ENT"),
	("DEN", "Dr. Yasmine Fathy", "Dental", "DEN"),
	("URO", "Dr. Tamer Fouad", "Urology", "URO"),
	("ONC", "Dr. Dina Ashraf", "Oncology", "ONC"),
	("PSY", "Dr. Hossam Gamal", "Psychiatry", "PSY"),
	("END", "Dr. Amr Zaki", "General Medicine", "END"),
	("GAS", "Dr. Walid Osman", "Gastroenterology", "GAS"),
	("PUL", "Dr. Heba Magdy", "General Medicine", "PUL"),
	("NEP", "Dr. Karim Badr", "General Medicine", "NEP"),
	("RHE", "Dr. Layla Nasser", "General Medicine", "RHE"),
	("INF", "Dr. Tarek Fouad", "General Medicine", "INF"),
	("PTH", "Dr. Mariam Youssef", "Physiotherapy", "PTH"),
	("SLP", "Dr. Salma Reda", "Physiotherapy", "SLP"),
	("OCC", "Dr. Nada Hesham", "Physiotherapy", "OCC"),
	("DIA", "Dr. Khaled Mostafa", "Nephrology", "DIA"),
	("RAD", "Dr. Youssef Anwar", "Radiology", "RAD"),
	("LAB", "Dr. Mona Adel", "Laboratory", "LAB"),
	("ER", "Dr. Ahmed Hassan", "Emergency Medicine", "ER"),
	("ANES", "Dr. Fatma Ali", "Anesthesia", "OT"),
]

SPECIALTY_LABEL_BY_CODE: dict[str, str] = {k: spec for k, _n, spec, _d in PRACTITIONERS}

CLINIC_ROTATION: list[tuple[str, str, str]] = [
	(dept, pr_key, spec)
	for pr_key, _name, spec, dept in PRACTITIONERS
	if dept not in ("RAD", "LAB", "PHM", "ER", "IPD", "ICU", "NICU", "CMP", "OT", "BBK", "CSS", "BME")
]

PATIENT_ROSTER: list[tuple[str, str, str, int]] = [
	("Ahmed", "Hassan", "male", 1982),
	("Fatma", "Ali", "female", 1990),
	("Mohamed", "Ibrahim", "male", 1975),
	("Nour", "Said", "female", 2005),
	("Khaled", "Mostafa", "male", 1968),
	("Mariam", "Youssef", "female", 1988),
	("Tarek", "Fouad", "male", 1995),
	("Hana", "Karim", "female", 2010),
	("Yasser", "Hamdy", "male", 1979),
	("Dina", "Ashraf", "female", 1993),
	("Samir", "Lotfy", "male", 1965),
	("Rania", "Ezz", "female", 1986),
	("Hossam", "Gamal", "male", 2000),
	("Salma", "Reda", "female", 1972),
	("Amr", "Zaki", "male", 1998),
	("Nada", "Hesham", "female", 2008),
	("Walid", "Osman", "male", 1980),
	("Heba", "Magdy", "female", 1991),
	("Karim", "Badr", "male", 1970),
	("Layla", "Nasser", "female", 1984),
	("Omar", "Fathy", "male", 1987),
	("Sara", "Kamal", "female", 1996),
	("Mahmoud", "Adel", "male", 1960),
	("Noha", "Sherif", "female", 1977),
	("Ibrahim", "Saeed", "male", 2003),
	("Yasmin", "Tarek", "female", 1985),
	("Hassan", "Nabil", "male", 1992),
	("Reem", "Osama", "female", 2001),
	("Fady", "Michel", "male", 1974),
	("Maha", "George", "female", 1969),
	("Peter", "Samy", "male", 1989),
	("Christine", "Botros", "female", 1994),
	("Ali", "Mahran", "male", 2006),
	("Zeinab", "Qassem", "female", 1983),
	("Mustafa", "Hamza", "male", 1971),
	("Aya", "Wael", "female", 1999),
	("Sherif", "Emad", "male", 1966),
	("Dalia", "Hany", "female", 1997),
	("Bassem", "Raouf", "male", 1981),
	("Ghada", "Mounir", "female", 1976),
	("Ehab", "Salem", "male", 1993),
	("Naglaa", "Farid", "female", 2004),
	("Ramy", "Sobhy", "male", 1988),
	("Inas", "Medhat", "female", 1973),
	("Wael", "Galal", "male", 1967),
	("Hend", "Ashraf", "female", 1995),
	("Sameh", "Nagy", "male", 2002),
	("Esraa", "Fouad", "female", 1991),
	("Mina", "Bishara", "male", 1986),
	("Lamia", "Ragab", "female", 1978),
]

WEB_SERVICES: list[tuple[str, str, str, str, float, str]] = [
	("CONS-FM", "Family Medicine Consultation", "FM", "FM", 300.0, "طب الأسرة — حجز عبر الموقع"),
	("CONS-GEN", "General Medicine Consultation", "GEN", "OPD", 350.0, "استشارة طب عام"),
	("CONS-CARD", "Cardiology Consultation", "CAR", "CARD", 500.0, "استشارة قلب"),
	("CONS-NEU", "Neurology Consultation", "NEU", "NEU", 480.0, "استشارة أعصاب"),
	("CONS-PED", "Pediatrics Consultation", "PED", "PED", 300.0, "عيادة أطفال"),
	("CONS-OBG", "OB/GYN Consultation", "OBG", "OBG", 420.0, "نساء وولادة"),
	("CONS-IVF", "Fertility Consultation", "IVF", "IVF", 600.0, "عقم وأطفال أنابيب"),
	("CONS-ORT", "Orthopedics Consultation", "ORT", "ORT", 400.0, "عظام"),
	("CONS-DER", "Dermatology Consultation", "DER", "DER", 350.0, "جلدية"),
	("CONS-DEN", "Dental Consultation", "DEN", "DEN", 400.0, "أسنان"),
	("CONS-ENT", "ENT Consultation", "ENT", "ENT", 380.0, "أنف وأذن وحنجرة"),
	("CONS-OPH", "Ophthalmology Consultation", "OPH", "OPH", 400.0, "عيون"),
	("CONS-URO", "Urology Consultation", "URO", "URO", 420.0, "مسالك بولية"),
	("CONS-ONC", "Oncology Consultation", "ONC", "ONC", 550.0, "أورام"),
	("CONS-PSY", "Psychiatry Consultation", "PSY", "PSY", 450.0, "طب نفسي"),
	("CONS-GAS", "Gastroenterology Consultation", "GAS", "GAS", 460.0, "جهاز هضمي"),
	("CONS-PTH", "Physiotherapy Session", "PTH", "PTH", 280.0, "علاج طبيعي"),
	("CONS-DIA", "Dialysis Session", "DIA", "DIA", 800.0, "غسيل كلى"),
	("PKG-DENTAL", "Dental Checkup Package", "DEN", "DEN", 500.0, "باقة فحص أسنان"),
	("LAB-CBC", "CBC Laboratory Panel", "LAB", "LAB", 250.0, "تحليل صورة دم"),
	("RAD-CXR", "Chest X-Ray", "RAD", "RAD", 450.0, "أشعة صدر"),
	("TEL-FU", "Telehealth Follow-up", "GEN", "OPD", 200.0, "متابعة عن بُعد"),
]

DEPARTMENT_WEB_ICONS: dict[str, str] = {
	"FM": "general",
	"OPD": "general",
	"CARD": "cardiology",
	"NEU": "neurology",
	"PED": "pediatrics",
	"NEO": "pediatrics",
	"OBG": "gynecology",
	"IVF": "gynecology",
	"ORT": "orthopedics",
	"SUR": "surgery",
	"DER": "dermatology",
	"OPH": "ophthalmology",
	"ENT": "ent",
	"DEN": "dentistry",
	"URO": "urology",
	"ONC": "oncology",
	"PSY": "psychiatry",
	"END": "endocrinology",
	"GAS": "gastroenterology",
	"PUL": "pulmonology",
	"NEP": "nephrology",
	"RAD": "radiology",
	"LAB": "lab",
	"PHM": "pharmacy",
	"ER": "emergency",
	"DIA": "dialysis",
}

DEFAULT_DEMO_PATIENTS = 50
MAX_DEMO_PATIENTS = 100
