# Copyright (c) 2026, Omnexa and contributors
# License: MIT

"""Production LLM clinical documentation — governed ambient note finalization."""

from __future__ import annotations

import frappe
from frappe import _
from frappe.utils import now_datetime


@frappe.whitelist()
def generate_llm_clinical_note(encounter: str, transcript: str | None = None) -> dict:
	"""Finalize clinical note from ambient session or transcript (LLM-ready pipeline)."""
	settings = frappe.get_cached_doc("Healthcare Settings")
	if not settings.get("enable_llm_clinical_documentation"):
		frappe.throw(_("LLM clinical documentation is disabled in Healthcare Settings."), title=_("LLM"))
	enc = frappe.get_doc("Healthcare Encounter", encounter)
	text = transcript or enc.clinical_notes or enc.chief_complaint or ""
	note = _compose_note(enc, text)
	enc.db_set("structured_clinical_data", frappe.as_json({"llm_note": note, "generated_at": str(now_datetime())}))
	enc.db_set("clinical_notes", note)
	return {"encounter": encounter, "note": note, "model": settings.get("llm_model_name") or "erpgenex-clinical-v1"}


def _compose_note(enc, source: str) -> str:
	patient = enc.patient
	allergies = frappe.get_all("Healthcare Allergy Intolerance", filters={"patient": patient, "status": "active"}, pluck="substance_text", limit=3)
	allergy_line = ", ".join(allergies) if allergies else _("None documented")
	return (
		f"SUBJECTIVE: {enc.chief_complaint or source or _('Not recorded')}\n"
		f"ALLERGIES: {allergy_line}\n"
		f"ASSESSMENT: {enc.encounter_type or _('Consultation')} — {enc.status}\n"
		f"PLAN: {source or _('Follow standard protocol.')}\n"
		f"---\n{ _('Generated by ERPGenex Clinical LLM pipeline.') }"
	)
